### ISSUE TITLE
Question - label pour les figures

### ISSUE THREAD

**Issue by DominiqueCaron** [BIO6032/2018_replication_hassell_1985#24]
@tpoisot devrait-on ajouter un label pour les figures avec plusieurs graphiques? Exemple un (a) dans le *panneau* de gauche et un (b) dans le *panneau* de droite pour la figure 3.

@vincelessard  et @QileWu  votre opinion?

**Comment by vincelessard** [comment]
Je crois que ce serait une bonne idée. Dans les captions, j'ai inscrit a), b), c), etc. alors il faudrait probablement l'indiquer.

**Comment by QileWu** [comment]
Je suis d'accord. C'est plus facile à lire et de l'identifier aussi pour moi.
